apiVersion: apps/v1
kind: Deploynent
metadata:
  name: roe-deployment
  labels:
    app: razor
spec:
  replicas: 4
  selector:
    matchLabels:
      app: razor 
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels: 
        app: razor 
    spec:
      containers:
      - name: raz-container
        image: shadowhub/raz:$(date +%Y%m%d_%H%M%S)
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.1"
            memory: 128Mi