apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata: 
  name: deployment-role
  namespace: dev 
rules:
- apiGroups: ["app", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "rollback"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-binding
  namespace: dev
subjects:
- kind: User
  name: deployment-team
  apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io/v1


























