name: Build and Deploy app

on:
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Generate image tag based on date and time
      id: datetime
      run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t shadowhub/raz:${{ steps.datetime.outputs.tag }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push shadowhub/raz:${{ steps.datetime.outputs.tag }}

    - name: Ensure .kube directory exists
      run: mkdir -p $HOME/.kube

    - name: Set permissions for .kube directory
      run: chmod 700 $HOME/.kube

    - name: Write Kubernetes config
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/

    - name: Deploy to EKS with Skaffold
      run: skaffold run
