name: Build and Deploy app

on:
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate image tag based on date and time
        id: datetime
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t shadowhub/raz:${{ steps.datetime.outputs.tag }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push shadowhub/raz:${{ steps.datetime.outputs.tag }}

      - name: Ensure .kube directory exists
        run: mkdir -p $HOME/.kube

      - name: Set permissions for .kube directory
        run: chmod 700 $HOME/.kube

      - name: Write Kubernetes config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Initialize Skaffold and Run
        run: |
            python3 - << EOF
            import subprocess
            
            # Perform Skaffold initialization
            init_command = "echo -e 'N\nN\ny' | skaffold init"
            subprocess.run(init_command, shell=True)
            
            # Confirm Skaffold initialization
            print("Skaffold initialization completed. Review the skaffold.yaml file if needed.")
            input("Press [Enter] to continue and run 'skaffold run'...")
            
            # Automatically press Enter
            subprocess.run("echo", shell=True)
            EOF
        
